# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-28 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20180328_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='desc',
            field=models.TextField(),
        ),
    ]
